---
apiVersion: v1
kind: Service
metadata:
  name: model-serving
  labels:
    app: model-serving
spec:
  type: NodePort
  selector:
    app: model-serving
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: model-serving
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
      - name: model-serving
        image: pqchat/model-serving:latest
        ports:
        - containerPort: 8080
