---
server:
  port: 8080

s3:
  accessKey:
  secretKey:
  bucketName:
  endpoint: s3.amazonaws.com

sentimentAnalysis:
  model: default-models/lreg-review-direct.zip
  columns: review,afterRelease,version,label

recommenderEngine:
  model: default-models/recommender-engine
  moviesPath: movielens/100k/u.item
  count: 10

modelType: sentiment

spring:
  application:
    name: analyze-sentiment
