---
server:
  port: 8080

s3:
  accessKey:
  secretKey:
  bucketName:
  endpoint: s3.amazonaws.com
  outputFile: model/lreg-direct.zip
  columns: text,afterRelease,hour,label

tf:
  modelLocation: http://dl.bintray.com/big-data/generic/minimal_graph.proto
  outputName: output/Softmax
  vocabLocation: http://dl.bintray.com/big-data/generic/vocab.csv

spring:
  application:
    name: analyze-sentiment
