---
server:
  port: 8080

s3:
  accessKey:
  secretKey:
  bucketName:
  endpoint: s3.amazonaws.com
  outputFile: model/lreg-review-direct.zip
  columns: review,afterRelease,version,label

tf:
  modelLocation: classpath:tensorflow/model/minimal_graph.proto
  outputName: output/Softmax
  vocabLocation: classpath:tensorflow/vocab.csv

spring:
  application:
    name: analyze-sentiment
