---
server:
  port: 8080

s3:
  accessKey:
  secretKey:
  bucketName:
  endpoint: s3.amazonaws.com

sentimentAnalysis:
  model: model/lreg-review-direct.zip
  columns: review,afterRelease,version,label

recommenderEngine:
  model: models/recommender-engine-new
  moviesPath: movielens/100k/u.item

spring:
  application:
    name: analyze-sentiment
