---
server:
  port: 8080

s3:
  accessKey:
  secretKey:
  bucketName:
  endpoint: s3.amazonaws.com
  outputFile: model/lreg-direct.zip
  columns: text,afterRelease,hour,label


spring:
  application:
    name: analyze-sentiment
