---
featureEngineering:
  featureJar: "jars/v2/feature-pipeline-direct.jar"
  dataPath: "app-reviews-partial.csv"
  featuresPath: "TestDataModel-direct.csv"
  columns: "review,afterRelease,version,label"
  funcJar: "feature-engineering/feature-engineering-sentiment-1.0-SNAPSHOT.jar"
  funcName: "net.mls.pipeline.feature.sentimentanalysis.ProcessReviewFn"


modelTraining:
  learningJar: "jars/v2/learning-pipeline-direct.jar"
  modelPath: "model/lreg-direct.zip"

modelServing:
  modelJar: "jars/model-serving.jar"
  kubeWfName: "model-endpoint-"

buildPush:
  dockerRepo: "pqchat"
  dockerImage: "model-serving"
  dockerVersion: "v4"

s3Endpoint: "s3.amazonaws.com"
s3Bucket: "argo-flow"