---
featureEngineering:
  featureJar: "jars/v-rec/feature-pipeline-direct.jar"
  dataPath: "app-reviews-partial.csv"
  featuresPath: "ReviewDataModel-direct.csv"
  columns: "review,afterRelease,version,label"
  funcJar: "feature-engineering/sa-reviews-tweets.jar"
  funcName: "net.mls.features.sentiment.ProcessReviewFn"
  runner: "DirectRunner"

modelTraining:
  learningJar: "jars/v-rec/learning-pipeline-direct.jar"
  modelPath: "model/lreg-review-direct.zip"
  runner: "DirectRunner"

modelServing:
  modelJar: "jars/v-rec/model-serving.jar"
  kubeWfName: "model-sa-endpoint-"
  enablePerformanceCollector: true
  performanceJar: "jars/v-serving/performance-collector.jar"
  enableABTesting: true
  abJar: "jars/v-serving/ab-service.jar"

buildPush:
  dockerRepo: "pqchat"
  dockerImage: "model-serving"
  dockerVersion: "v1"

s3Endpoint: "s3.amazonaws.com"
s3Bucket: "argo-flow"
modelType: "sentiment"