---
featureEngineering:
  featureJar: "jars/v2/feature-pipeline-direct.jar"
  dataPath: "app-reviews-partial.csv"
  featuresPath: "ReviewDataModel-direct.csv"
  columns: "review,afterRelease,version,label"
  funcJar: "feature-engineering/sa-reviews-tweets.jar"
  funcName: "net.mls.features.sentiment.ProcessReviewFn"
  runner: "DirectRunner"


modelTraining:
  learningJar: "jars/v2/learning-pipeline-direct.jar"
  modelPath: "model/lreg-review-direct.zip"
  runner: "DirectRunner"

modelServing:
  modelJar: "jars/v2/model-serving.jar"
  kubeWfName: "model-endpoint-"

buildPush:
  dockerRepo: "pqchat"
  dockerImage: "model-serving"
  dockerVersion: "v4"

s3Endpoint: "s3.amazonaws.com"
s3Bucket: "argo-flow"