---
featureEngineering:
  featureJar: "jars/feature-pipeline-direct.jar"
  dataPath: "chase_ios_app_reviews-partial.csv"
  featuresPath: "TestDataModel-direct.csv"

modelTraining:
  learningJar: "jars/learning-pipeline-direct.jar"
  modelPath: "model/lreg-direct.zip"

modelServing:
  modelJar: "jars/model-serving.jar"
  kubeWfName: "model-endpoint-"

buildPush:
  dockerRepo: "pqchat"
  dockerImage: "model-serving"
  dockerVersion: "v2"

s3Endpoint: "s3.amazonaws.com"
s3Bucket: "argo-flow"