---
featureEngineering:
  featureJar: "jars/v-rec/feature-pipeline-direct.jar"
  dataPath: "app-reviews-partial.csv"
  featuresPath: "ReviewDataModel-direct.csv"
  columns: "review,afterRelease,version,label"
  funcJar: "feature-engineering/sa-reviews-tweets.jar"
  funcName: "net.mls.features.sentiment.ProcessReviewFn"
  runner: "DirectRunner"

modelTraining:
  learningJar: "jars/v-rec/learning-pipeline-direct.jar"
  modelPath: "model/lreg-review-direct.zip"
  runner: "DirectRunner"

modelServing:
  modelJar: "jars/v-serving/v3/model-service.jar"
  kubeWfName: "model-sa-endpoint-"
  enableStats: true
  statsJar: "jars/v-serving/v3/stats-service.jar"
  enableProcessor: true
  processorJar: "jars/v-serving/v3/processor-service.jar"

buildPush:
  dockerRepo: "pqchat"
  dockerImage: "model-serving"
  dockerVersion: "v1"

s3Endpoint: "s3.amazonaws.com"
s3Bucket: "argo-flow"
modelType: "sentiment"
pipelineType: "serving" # building , building-serving